---
# Install and setup PostgreSQL with Streaming Replication
- hosts: all
  become: yes
  become_user: root
  vars:
    - postgresql_users
    - postgresql_streaming_user
    - postgresql_users
  vars_files:
    - 'defaults/main.yml'
    - 'defaults/repo.yml'
  tasks:
  - include: 'tasks/install.yml'

- hosts: streaming-master
  become: yes
  become_user: root
  vars_files:
    - 'defaults/main.yml'
  tasks:
  - group_by: key=os_{{ ansible_os_family }}
  - include: 'tasks/configure-master.yml'
  - include: 'tasks/users.yml'
  - include: 'tasks/databases.yml'

- hosts: streaming-slaves
  become: yes
  become_user: root
  vars_files:
    - 'defaults/main.yml'
  tasks:
  - group_by: key=os_{{ ansible_os_family }}
  - include: 'tasks/configure-slaves.yml'
